apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-frame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-frame
  template:
    metadata:
      labels:
        app: get-frame
    spec:
      containers:
        - name: get-frame
          image: mjsoto123/get-frame
          ports:
            - containerPort: 5003
          volumeMounts:
            - name: video-storage
              mountPath: /app/data
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
