apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
