apiVersion: v1
kind: Service
metadata:
  name: get-video
  annotations:
  labels:
    app: get-video
spec:
  type: ClusterIP
  selector:
    app: get-video
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
